name: Agent Scan
description: A GitHub action that helps detecting if a contributor is an AI agent.
author: Jens Rømer Hesselbjerg

branding:
  icon: alert-circle
  color: 'gray-dark'

inputs:
  github-token:
    description: 'The GitHub token for authentication.'
    required: true
    default: ${{ github.token }}
  pr-number:
    description: 'The number of the pull request to comment on.'
    required: true
    default: ${{ github.event.pull_request.number }}

runs:
  using: node24
  main: dist/index.js
